export enum ActionTypes {
    GET_STORIES_PENDING = 'GET_STORIES_PENDING',
    GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS',
    GET_STORIES_FAILED = 'GET_STORIES_FAILED',
    GET_ITEM_PENDING = 'GET_ITEM_PENDING',
    GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILED = 'GET_ITEM_FAILED',
    GET_ITEM_DONE = 'GET_ITEM_DONE',
    GET_USER_PENDING = 'GET_USER_PENDING',
    GET_USER_SUCCESS = 'GET_USER_SUCCESS',
    GET_USER_FAILED = 'GET_USER_FAILED',
    GET_USER_DONE = 'GET_USER_DONE',
}